# Generated by Django 4.1.7 on 2023-04-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('remotePosition', models.BooleanField(blank=True, null=True)),
                ('positionFilled', models.BooleanField(blank=True, null=True)),
                ('featuredListing', models.BooleanField(blank=True, null=True)),
                ('importantInformation', models.CharField(max_length=200)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('applicationLinkOrEmail', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('companyname', models.CharField(max_length=200)),
            ],
        ),
    ]
