# Generated by Django 4.2.1 on 2023-07-25 08:43

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="positionFilled",
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
