# Generated by Django 4.1.7 on 2023-04-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_job_companylogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='seodescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
