# Generated by Django 4.2.1 on 2023-07-25 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_job_positionfilled_alter_job_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="remotePosition",
        ),
    ]
