# Generated by Django 4.1.7 on 2023-04-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_job_seodescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='companylogo',
            field=models.ImageField(default='logo.png', null=True, upload_to=''),
        ),
    ]
