# Generated by Django 4.1.7 on 2023-04-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_job_importantinformation_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.jobcategories'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.jobtypes'),
        ),
    ]
