# Generated by Django 4.2.1 on 2023-07-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_remove_job_remoteposition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="jobCategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.jobcategories",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="jobType",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.jobtypes",
            ),
        ),
    ]
