# Generated by Django 4.1.7 on 2023-04-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_job_jobcategory_alter_job_jobtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobCategory',
        ),
        migrations.AddField(
            model_name='job',
            name='jobCategory',
            field=models.ManyToManyField(to='base.jobcategories'),
        ),
    ]
