# Generated by Django 4.2.1 on 2023-07-25 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_job_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="user",
            new_name="posted_by",
        ),
    ]
