# Generated by Django 4.1.7 on 2023-04-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_job_jobcategory_job_jobcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='job',
            name='companylogo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobCategory',
            field=models.ManyToManyField(blank=True, null=True, to='base.jobcategories'),
        ),
    ]
