# Generated by Django 4.1.7 on 2023-04-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_job_options_job_companylogo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobType',
        ),
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.ManyToManyField(blank=True, null=True, to='base.jobtypes'),
        ),
    ]
