# Generated by Django 4.1.7 on 2023-04-16 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_job_jobtype_job_jobtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobType',
        ),
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.jobtypes'),
        ),
    ]
