# Generated by Django 4.1.7 on 2023-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, default='NoImage.jpg', null=True, upload_to=''),
        ),
    ]
