# Generated by Django 4.1.7 on 2023-05-09 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='tracking',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
