# Generated by Django 4.1.7 on 2023-05-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_tracking_alter_resume_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialLink',
            new_name='SocialLinks',
        ),
    ]
