# Generated by Django 4.1.7 on 2023-05-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_sociallinks_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
    ]
