# Generated by Django 4.1.7 on 2023-05-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_remove_resume_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, default='NoImageBlue.jpg', null=True, upload_to=''),
        ),
    ]
