# Generated by Django 4.1.7 on 2023-05-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_resume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(blank=True, default='NoImageBlue.png', null=True, upload_to=''),
        ),
    ]
